# name: mini-pern-dev
services:
  postgres:
    image: postgres:14
    container_name: mini-pern-dev_postgres
    environment:
      - POSTGRES_PASSWORD
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    volumes:
      - type: bind
        source: ./database/config.sh
        target: /docker-entrypoint-initdb.d/config.sh
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    networks:
      - localnet

  app:
    depends_on:
      - postgres
    image: jhordyess/node:18
    container_name: mini-pern-dev
    volumes:
      - .:/mini-pern:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - DATABASE_URL
    networks:
      - localnet

volumes:
  postgres-data:


networks:
  localnet:
    driver: bridge
