services:
  pg-sql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    volumes:
      - ./build/database/config.sh:/docker-entrypoint-initdb.d/config.sh
  backend:
    image: jhordyess/node:16
    volumes:
      - .:/mini-pern:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - BACKEND_PATH=/mini-pern/backend
      - DATABASE_URL
    ports:
      - "4062:4062"
  frontend:
    image: jhordyess/node:16
    volumes:
      - .:/mini-pern:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3640:3640"
