services:
  postgres:
    image: postgres
    container_name: mini-pern_postgres
    environment:
      - POSTGRES_PASSWORD
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    volumes:
      - ./database/config.sh:/docker-entrypoint-initdb.d/config.sh
  pga:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    ports:
      - "80-90:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
  node:
    depends_on:
      - postgres
    image: jhordyess/node
    container_name: mini-pern_node
    volumes:
      - .:/mini-pern:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - DATABASE_URL
    ports:
      - "4062-4072:4062"
      - "3640-3650:3640"
