#!/bin/bash
# Create role
psql -v ON_ERROR_STOP=1 -U postgres <<EOSQL
CREATE ROLE "${DB_USER}" WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '${DB_PASSWORD}';
EOSQL
# Create database
psql -v ON_ERROR_STOP=1 -U postgres <<EOSQL
CREATE DATABASE "${DB_NAME}"
  WITH 
  OWNER = "${DB_USER}"
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
EOSQL
# Grant permissions
psql -v ON_ERROR_STOP=1 -U postgres -d ${DB_NAME} <<EOSQL
GRANT ALL ON ALL TABLES IN SCHEMA public TO "${DB_USER}";
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "${DB_USER}";
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO "${DB_USER}";
EOSQL
